let data = [
  {
    id: 1,
    product: "Jockey t-shirt",
    type: "t-shirt",
    color: "blue",
    img: "./images/blue-tshirt.webp",
    price: "399",
    count: 0,
  },
  {
    id: 2,
    product: "worng",
    type: "t-shirt",
    color: "green",
    img: "./images/green-tshirt.jpeg",
    price: "577",
    count: 0,
  },
  {
    id: 3,
    product: "mufti",
    type: "t-shirt",
    color: "red",
    img: "./images/polo-green-t-shirt.jpg",
    price: "999",
    count: 0,
  },
  {
    id: 4,
    product: "BTS",
    type: "t-shirt",
    color: "Yellow",
    img: "./images/yellow-t-shirt-BTS.webp",
    price: "888",
    count: 0,
  },
  {
    id: 5,
    product: "Black & white",
    type: "t-shirt",
    color: "black",
    img: "./images/Black-t-shirt.webp",
    price: "499",
    count: 0,
  },
  {
    id: 6,
    product: "Baggy",
    type: "Jeans",
    color: "Blue",
    img: "./images/jeansBlue.jpeg",
    price: "699",
    count: 0,
  },
  {
    id: 7,
    product: "Jeans",
    type: "light Blue",
    color: "blue",
    img: "/images/jeansBaggyJogger.webp",
    price: "2299",
    count: 0,
  },
  {
    id: 8,
    product: "how&here",
    type: "Jeans",
    color: "blue",
    img: "./images/lightBlue-jeans.webp",
    price: "2900",
    count: 0,
  },
  {
    id: 9,
    product: "lee",
    type: "jeans",
    color: "green",
    img: "./images/greenJeans.avif",
    price: "4000",
    count: 0,
  },
  {
    id: 10,
    product: "titan black",
    type: "watch",
    color: "black",
    img: "./images/watch-for-women.webp",
    price: "5020",
    count: 0,
  },
  {
    id: 11,
    product: "titan",
    type: "watch",
    color: "golden",
    img: "./images/golden-watch-titen.webp",
    price: "7999",
    count: 0,
  },
  {
    id: 12,
    product: "titan",
    type: "watch",
    color: "green",
    img: "./images/titin-green-watch.avif",
    price: "9999",
    count: 0,
  },
  {
    id: 13,
    product: "fireBolt",
    type: "smart watch",
    color: "orange",
    img: "./images/smart-watch-oranges.webp",
    price: "5999",
    count: 0,
  },
  {
    id: 14,
    product: "boat",
    type: "watch",
    color: "orange and white",
    img: "./images/smart-watch-2023.webp",
    price: "11990",
    count: 0,
  },
  {
    id: 15,
    product: "bacca",
    type: "shoes",
    color: "white",
    img: "./images/white-shoes.webp",
    price: "12000",
    count: 0,
  },
  {
    id: 16,
    product: "HRX",
    type: "shoes",
    color: "blue",
    img: "./images/hrx-shoes-for-men.avif",
    price: "2800",
    count: 0,
  },
  {
    id: 17,
    product: "brogue",
    type: "shoes",
    color: "brown",
    img: "./images/brown-leather-shoes.jpg",
    price: "5999",
    count: 0,
  },
  {
    id: 18,
    product: "fila",
    type: "shoes",
    color: "black",
    img: "./images/black-shoes-fila.jpg",
    price: "8000",
    count: 0,
  },
  {
    id: 19,
    product: "china sneakers",
    type: "loafer",
    color: "brown",
    img: "./images/brown-leather-shoes.jpg",
    price: "2500",
    count: 0,
  },
  {
    id: 20,
    product: "stockX",
    type: "expensive shoes",
    color: "white",
    img: "./images/most-expensive-sneakers.avif",
    price: "40000",
    count: 0,
  },
];

export { data };
